apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sync
  namespace: default
spec:
  encryptedData:
    credentials.password: AQA3gzXB3HksW8Z6Oh+sUHAYGg+Q3K5Ap+iCc5mkuoP9g/uI6FKsBZckr+XK4Dmu/iqTOFdZva6pBOAONHH/Mnl/Lsxvy+Aapdzwj+H7TG+YpyvX1gCy42kz3aJ3Ga/YuhAr9Xg1dc5C4JtFdVVr5eowtpsxakdJdTG/gzCKhfVWHq66VBJJBcDu9jIhfs1YZ1QIabP+Ad4WwTKwKODsZEVjRX8dLdIeNKP+UiX7bHlkAWJmorBgfAn/Ya69iLI+HTZTnrBZgxkfP9J4cZwUAqpn/zQ5fftzOCghjN1+ZiTe6TzAB12a+DF8A8k+Q6nNsgJIbXLoq3VAjnBlg+Uc/ZSAc6Y42uus9uu0wY3n624Dj87V86AUiwYZd0uK8rsAnhU/61lfZeT4m4uvjO7GkqWVlepF2hvmcxg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: sync
      namespace: default

