apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: giri-eks-np-qc1
  project: giri
spec:
  blueprintConfig:
    name: new-bp
    version: version1
  cloudCredentials: new
  config:
    metadata:
      name: giri-eks-np-qc1
      region: us-west-2
      version: "1.21"
    network:
      cni:
        name: aws-cni
    nodeGroups:
    - amiFamily: AmazonLinux2
      desiredCapacity: 3
      iam:
        withAddonPolicies:
          autoScaler: true
          imageBuilder: true
      instanceType: t3.large
      maxSize: 3
      minSize: 3
      name: ng-bb3d0ba5
      version: "1.21"
      volumeSize: 80
      volumeType: gp3
    vpc:
      cidr: 192.168.0.0/16
      clusterEndpoints:
        privateAccess: false
        publicAccess: true
      nat:
        gateway: Single
  proxyConfig: {}
  type: aws-eks
