apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: test
  project: giri
spec:
  active: true
  sharing:
    enabled: false
  stages:
  - config:
      destinationRepo:
        repository: sync
        revision: main
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        repository: sync
        revision: main
      systemToGitSync: true
    name: test
    type: SystemSync
