apiVersion: v1
kind: Pod
metadata:
  name: webserver1
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: giri
      mountPath: /usr
  volumes:
  - name: giri
    persistentVolumeClaim:
      claimName: testclaim
