apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: giri-params
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBgPI2PuxBitpAEEs2p6nBWEzHhgfqR15oGla5yJS3/xg+EA+dajhONlcyTT9FTfuO1wIGos8CB8WZGUw9yjMItcIPkk2LBMWRgXISYoJQqU6Ta+evJXRlaU+vh4FRL50KWt/NsLlYhPYthlZeufm7wYzEvk3UcP6oO+2JdbVqCeQXIygQS7Zl8jtTAzIgiUmruxlbHTXJcXEPl6wcBG8JForReFJBljsxI4hCgh+03PTkcBf+ge0gxEr9evgyFfjvIb9wfe/CgmDAtzs+J+rn19eSWq9BHPGT/FKqVJ10+UnxZArzpO/ub5sL6z+3KrMG8qljjrXugn/PzTtdYg6ri4CZLdfSaglZbUIwjn6TGMjyArCnvBxSPrhDSmH1/6srNAVfH9MDxR4+3fEAIlvvuP527HJMIGls=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: giri-params
      namespace: default

