apiVersion: infra.k8smgmt.io/v3
kind: Namespace
metadata:
  name: message
  project: giri
spec:
  drift:
    enabled: false
  limitRange:
    container: {}
    pod: {}
  namespaceMeshPolicyParams: {}
  placement:
    labels:
    - key: rafay.dev/clusterName
      value: giri-eks1-qc
    - key: rafay.dev/clusterName
      value: giri-aws-calico-cni
    - key: rafay.dev/clusterName
      value: giri-eks-np-qc1
  resourceQuotas: {}
