apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: new-addon
  project: giri
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/new-addon/nginx-pod.yaml
    options: {}
    type: Yaml
  namespace: message
  sharing:
    enabled: false
  version: nginx
