apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cilium-blocker
spec:
  endpointSelector:
    matchLabels:
      org: empire
      class: deathstar
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
        protocol: TCP
