apiVersion: apps.k8smgmt.io/v3
kind: Workload
metadata:
  name: testing
  project: giri
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/testing/testing.yaml
    options: {}
    type: Yaml
  drift:
    enabled: false
  namespace: cilium-test
  placement:
    selector: rafay.dev/clusterName=giri-rafay-eks
  version: testing-v1
